export interface BlogPost {
  slug: string;
  title: string;
  excerpt: string;
  featured: boolean;
  category: string;
  readTime: string;
  date: string;
  dateISO: string;
  content: string[];
}

export const blogPosts: BlogPost[] = [
  {
    slug: "complete-guide-mobile-home-park-insurance",
    title: "Complete Guide to Mobile Home Park Insurance",
    excerpt:
      "Everything mobile home park and manufactured housing community owners need to know about commercial insurance — coverage types, costs, how to get the right policy, and what to expect at claims time.",
    featured: true,
    category: "Insurance Guides",
    readTime: "12 min read",
    date: "June 10, 2026",
    dateISO: "2026-06-10",
    content: [
      "Mobile home park insurance is one of the most misunderstood segments of commercial property coverage. Most general insurance agents have limited experience with manufactured housing communities, which means park owners often find themselves either underinsured, overcharged, or holding a policy that excludes the exact risks their business faces. This guide explains everything you need to know.",
      "## What Is Mobile Home Park Insurance?",
      "Mobile home park insurance — sometimes called manufactured housing community (MHC) insurance or trailer park insurance — is a commercial lines policy designed specifically for the unique risks of owning and operating a residential community where tenants own or rent manufactured homes on leased lots. Unlike standard commercial property insurance, a properly structured MHP policy accounts for shared infrastructure, common area liability, lot rent revenue, and the complex legal landscape governing manufactured housing.",
      "The term 'mobile home park insurance' covers a spectrum of community types: traditional parks with older HUD-code homes, modern manufactured housing communities with site-built-quality homes, age-restricted (55+) retirement communities, and mixed-use parks that include both manufactured homes and recreational vehicles. Each type carries slightly different risk profiles, but the core coverage needs are similar.",
      "## Property Coverage: Protecting Your Physical Assets",
      "A mobile home park's physical assets include far more than the homes themselves — which, in most cases, belong to the tenants. Your insurable property as the park owner includes the land improvements, the common area buildings, utility infrastructure, and any park-owned homes or rental units you operate directly.",
      "Common area buildings — clubhouses, laundry facilities, management offices, maintenance sheds, and recreational amenities like pools or playgrounds — should be covered on a replacement cost basis. Replacement cost coverage pays what it actually costs to rebuild or replace, rather than the depreciated 'actual cash value.' For older infrastructure, the difference between these two valuations can be dramatic, leaving park owners with significant out-of-pocket costs after a loss.",
      "Utility infrastructure is often the most significant and most overlooked component of MHP property coverage. Water mains, sewer laterals, electrical distribution systems, gas lines, and roadways represent millions of dollars in replacement value at a typical community. Underground infrastructure requires specific coverage endorsements — standard commercial property policies often exclude below-grade utilities. A specialist MHP insurer will offer coverage that explicitly includes these systems.",
      "## General Liability Coverage for Park Owners",
      "General liability (GL) insurance protects you when someone is injured or their property is damaged on your premises, or when your business operations cause harm to a third party. For mobile home park owners, GL coverage is not optional — it is the foundation of your risk management program.",
      "Common liability claims in mobile home parks include slip-and-fall accidents in common areas, injuries at recreational amenities such as pools or playgrounds, tenant claims arising from utility failures or infrastructure defects, and third-party property damage from fallen trees, flooding, or fire spread. A well-structured GL policy with adequate limits is essential for all of these scenarios.",
      "## Loss of Rents Coverage",
      "Loss of rents coverage — also called business income or rent loss insurance — replaces the lot rents you cannot collect while your property is being repaired after a covered loss. If a storm damages infrastructure and forces you to reduce or suspend lot rent collections, this coverage steps in to replace that lost income for the duration of the repair period.",
      "For mobile home parks, loss of rents is particularly important because infrastructure failures can displace multiple tenants simultaneously. A water main break or electrical failure may affect dozens of lots at once, and if conditions become uninhabitable, you may be required by law to reduce or abate rent. Loss of rents coverage bridges that gap.",
      "## Flood Insurance Considerations",
      "Many mobile home parks sit in or near flood-prone areas — historically, affordable land for manufactured housing communities was often land that carried flood risk. Standard commercial property policies exclude flood damage, which means park owners need to purchase flood insurance separately.",
      "The National Flood Insurance Program (NFIP) offers coverage for buildings and some contents, but NFIP limits (currently $500,000 per building) may be insufficient for larger community facilities. Private flood insurance, available through specialty carriers, can offer higher limits, broader coverage, and faster claims processing. A specialist MHP insurance broker will evaluate your flood zone designation and recommend the appropriate combination of NFIP and private flood coverage.",
      "## What Affects Your Premium?",
      "Mobile home park insurance premiums are calculated based on a variety of factors: the total replacement value of your insurable property, the number of lots and current occupancy rate, the age and condition of utility infrastructure, your community's flood zone designation, your loss history for the past five years, the state where the park is located (regulatory environment and weather risk vary significantly), and the types of amenities and recreational facilities you operate.",
      "Parks with older infrastructure, high-value amenities like swimming pools, or locations in hurricane or tornado corridors will pay higher premiums. However, proactive risk management — documented inspection programs, updated electrical systems, ADA-compliant pathways, and controlled-access swimming areas — can significantly reduce your premium over time.",
      "## The Claims Process",
      "When a loss occurs at your mobile home park, your insurer will assign an adjuster to assess the damage and determine coverage. Document everything immediately: photograph all damage, secure the area if necessary, and notify your insurer within the timeframe specified in your policy (typically 24-72 hours). Keep records of all emergency expenses — temporary repairs, tenant relocation costs, professional cleanup — as these may be reimbursable.",
      "Working with a specialist MHP insurer makes a meaningful difference at claims time. Adjusters who understand manufactured housing communities know what replacement costs actually look like, understand the relationship between infrastructure damage and lot rent abatement, and can move the process forward efficiently. An adjuster unfamiliar with MHP operations may undervalue losses or apply exclusions that don't apply to your specific policy.",
      "## How to Get the Right Coverage",
      "The single most important step in securing appropriate mobile home park insurance is working with an agent who specializes in this niche. A specialist brings carrier relationships that general agents don't have, understands the specific endorsements that MHPs require, and can help you structure a program that genuinely protects your investment rather than just checking a compliance box. Contact Contractors Choice Agency at 844-967-5247 for a no-obligation review of your current coverage and a competitive quote.",
    ],
  },
  {
    slug: "mobile-home-park-liability-risks",
    title: "The Top Liability Risks for Mobile Home Park Owners",
    excerpt:
      "From slip-and-fall accidents to utility failures and discrimination claims, mobile home park owners face a complex web of liability exposures. Here is what you need to know to protect your business.",
    featured: false,
    category: "Risk Management",
    readTime: "9 min read",
    date: "June 5, 2026",
    dateISO: "2026-06-05",
    content: [
      "Running a mobile home park or manufactured housing community means managing a complex web of liability exposures that most property owners never have to think about. You are simultaneously a landlord, a utility provider, an infrastructure operator, and a community manager — and each of those roles carries its own set of legal and financial risks. Understanding the top liability threats to your business is the first step toward managing them effectively.",
      "## Slip and Fall Accidents in Common Areas",
      "Slip-and-fall accidents are the single most common source of general liability claims in mobile home parks. Ice on uncleared walkways, potholes in park roads, uneven pavement near clubhouse entrances, and poor lighting in common areas all create conditions where residents, guests, and visitors can be injured — and where you can be held financially responsible.",
      "The key to managing slip-and-fall risk is documentation and consistency. Maintain a written inspection schedule for all common area surfaces, record each inspection in a dated log, and photograph any defect along with the repair made to correct it. Courts look at whether a property owner knew or should have known about a hazardous condition. A documented inspection program demonstrates reasonable care and can be a powerful defense in litigation.",
      "## Utility Failures and Infrastructure Defects",
      "As the park owner, you are typically responsible for maintaining the shared utility infrastructure — water mains, sewer laterals, electrical distribution, gas lines — that serves all lots in the community. When these systems fail, the consequences can extend far beyond inconvenience.",
      "A broken water main that floods several lots can damage tenant property. A sewage backup that renders units uninhabitable triggers both property damage claims and habitability disputes. An electrical failure that causes a fire can result in catastrophic personal injury and property damage claims. Worse, if a tenant can demonstrate that you had notice of a defect and failed to repair it, courts may apply punitive damages in addition to compensatory awards.",
      "The risk management approach here is twofold: maintain infrastructure proactively (scheduled inspections, documented repairs, professional system upgrades) and carry adequate general liability coverage with appropriate limits. For large communities, umbrella or excess liability coverage above your primary GL policy is essential.",
      "## Fair Housing and Discrimination Claims",
      "The Fair Housing Act prohibits discrimination in the rental of housing on the basis of race, color, national origin, religion, sex, familial status, and disability. For manufactured housing communities, fair housing claims are a significant and often underappreciated liability exposure.",
      "Common fair housing issues in mobile home parks include inconsistent application of park rules across different tenant groups, refusal to make reasonable accommodations for disabled tenants (such as allowing assistive animals or accessible parking), age restrictions applied improperly in communities that are not properly qualified as 55+ housing, and discriminatory advertising or tenant screening practices.",
      "Fair housing violations can result in substantial monetary damages, attorney fee awards, and injunctive relief. Defense costs alone — even in cases where you ultimately prevail — can reach six figures. Employment practices liability and commercial general liability policies typically exclude fair housing claims, which means you may need separate civil rights liability coverage or a specifically endorsed GL policy.",
      "## Dog Bites and Pet-Related Incidents",
      "Many mobile home parks allow pets, and dog bites are a significant source of liability claims. In states with strict liability for dog owners, the dog owner's liability insurance (typically a renter's policy) is the first line of defense. However, park owners can face liability if they were aware of a dangerous animal on the property and failed to take action.",
      "A clear, consistently enforced pet policy — with breed restrictions where appropriate, size limits, and vaccination requirements — reduces both the likelihood of incidents and your potential liability exposure. Require tenants to carry renter's insurance with liability coverage, and document any complaints about specific animals in writing.",
      "## Pool and Recreational Facility Liability",
      "Swimming pools, playgrounds, and other recreational amenities dramatically increase your liability exposure. Drowning claims, diving injuries, pool-related infections, and playground injuries are all potential sources of significant litigation.",
      "The mitigation strategies are well-established: compliant pool fencing and self-latching gates, clearly posted rules and depth markings, regular equipment inspections, liability releases where appropriate (though these are of limited value in many states), and adequate supervision policies. Playgrounds should meet current ASTM safety standards, and equipment should be inspected and maintained on a documented schedule.",
      "## ADA Compliance Obligations",
      "The Americans with Disabilities Act and Section 504 of the Rehabilitation Act impose accessibility requirements on mobile home parks that receive federal funding or that constitute public accommodations. Even communities that do not fall under federal ADA requirements may be subject to state accessibility laws, and the failure to make reasonable accommodations for disabled tenants is a fair housing violation.",
      "Common ADA-related issues in MHPs include inaccessible clubhouse entrances, lack of accessible parking near common facilities, pool lifts and accessible routes to amenities, and the obligation to allow disabled tenants to make reasonable accessibility modifications to their lots. Non-compliance can result in federal enforcement actions, private litigation, and significant remediation costs.",
      "## Security and Criminal Activity",
      "If criminal activity occurs on your property and a tenant or visitor is harmed, you may face negligent security claims if you knew or should have known about the security risk and failed to take reasonable steps to address it. This exposure is particularly significant in communities that have experienced prior incidents.",
      "Reasonable security measures include adequate lighting in all common areas, controlled access gates where appropriate, clearly posted security policies, and prompt response to tenant complaints about suspicious activity. Document all security-related incidents and your responses to them. Consider periodic professional security assessments for larger communities.",
      "Contractors Choice Agency helps mobile home park owners build comprehensive general liability programs that address all of these exposures. Call 844-967-5247 to discuss your specific situation and get a competitive insurance quote.",
    ],
  },
  {
    slug: "rv-park-insurance-requirements",
    title: "RV Park & Campground Insurance: What Owners Need to Know",
    excerpt:
      "RV parks and campgrounds face insurance challenges that are distinct from traditional mobile home parks. Transient guests, hookup liability, seasonal operations, and workers compensation all require careful attention.",
    featured: false,
    category: "RV Parks",
    readTime: "8 min read",
    date: "May 28, 2026",
    dateISO: "2026-05-28",
    content: [
      "RV parks and campgrounds occupy a unique niche in the commercial insurance landscape. Unlike mobile home parks — where tenants have long-term leases and a more settled relationship with the property — RV parks deal with transient guests who may stay for a single night, a week, or an entire season. That transient nature creates insurance challenges that standard commercial property and liability policies are often ill-equipped to handle.",
      "## The Transient Guest Problem",
      "When a guest at your RV park suffers an injury or property damage, you may face liability regardless of whether the guest's own negligence contributed to the incident. Transient guests — unlike long-term tenants — are less familiar with your property, may have impaired judgment (particularly at destination campgrounds where alcohol consumption is common), and are more likely to wander into areas that are not intended for guest access.",
      "General liability insurance for RV parks and campgrounds must be structured to address this transient population. Your policy should specifically cover guest injuries in common areas, injuries arising from the use of hookup equipment (electrical pedestals, water connections, sewer dump stations), recreational amenity injuries at pools, game courts, and nature trails, and property damage caused by other guests or park operations.",
      "## Electrical Hookup Liability",
      "Electrical hookup liability is one of the most significant and least understood exposures for RV park owners. Modern recreational vehicles draw substantial electrical loads, and substandard or deteriorating electrical infrastructure creates genuine electrocution and fire risk. When a guest's RV is damaged or a guest is injured due to a faulty electrical pedestal, park owners face significant liability.",
      "The standard of care for electrical infrastructure in RV parks is well-established: GFCI protection on all pedestals, regular testing and maintenance by licensed electricians, documented inspection records, and prompt replacement of damaged or aging equipment. Parks that fail to meet this standard — particularly after receiving complaints about electrical issues — face not only negligence liability but potentially punitive damages.",
      "Your GL policy should specifically include coverage for electrical hookup liability, and you should confirm with your insurance professional that your policy does not contain exclusions that would eliminate this coverage in the event of an electrical incident.",
      "## Property Coverage: What Needs to Be Insured",
      "RV park property coverage needs are somewhat different from traditional mobile home parks. Common insurable property at an RV park includes the reception and registration building, bathhouse and restroom facilities, laundry facilities, camp store or convenience facilities, recreational amenities (pools, courts, playgrounds), utility infrastructure (electrical distribution, water, sewer), and any rental units (cabins, glamping accommodations, park-model RVs) that you operate directly.",
      "The rising popularity of 'glamping' — glamorous camping with premium accommodations like safari tents, yurts, and deluxe park-model units — has expanded the insurable property profile for many RV park operators. Premium accommodations represent significant per-unit investment and should be covered at replacement cost with appropriate contents coverage.",
      "## Seasonal Operations and Coverage Gaps",
      "Many RV parks and campgrounds operate seasonally, closing during winter months when weather conditions make camping impractical. Seasonal closures create specific insurance considerations that park owners must address proactively.",
      "First, vacancy or seasonal closure does not typically reduce your liability exposure — a vandal who is injured on your property during the off-season may still have a claim. Many commercial liability policies include vacancy clauses that limit coverage after extended periods of non-occupancy. Review your policy language carefully and discuss your operating season with your insurance agent.",
      "Second, property losses during the off-season — particularly water damage from frozen pipes, theft, and vandalism — may be more severe because they go undetected longer. Maintain adequate property coverage throughout the year, not just during operating season, and consider regular off-season inspections to catch losses early.",
      "## Workers Compensation for Park Staff",
      "RV park and campground operations typically require year-round or seasonal employees: maintenance technicians, front-desk staff, groundskeepers, and sometimes food service or retail employees. Workers compensation insurance is required in virtually all states for employers with any employees, and the penalties for operating without it can be severe.",
      "Workers comp covers medical costs and lost wages for employees injured on the job. For RV park operations, common workers comp claims include injuries from maintenance work (falls, equipment injuries, electrical exposure), groundskeeping injuries (equipment accidents, repetitive stress), and guest-service injuries. Maintain a documented safety program, conduct regular safety training, and report all workplace injuries promptly to keep your workers comp experience modification factor manageable.",
      "## Liquor Liability and Event Coverage",
      "Many RV parks host community events — holiday gatherings, themed weekends, outdoor concerts — that involve alcohol service. Liquor liability coverage is essential if your park serves or allows the sale of alcoholic beverages at any event. Host liquor liability covers your exposure when alcohol you served contributes to a guest's injury or third-party harm.",
      "Special event coverage may also be appropriate for larger gatherings. Standard GL policies may exclude coverage for events above a certain attendance threshold, and you should discuss your event programming with your insurance agent to ensure adequate coverage.",
      "Contractors Choice Agency has been helping RV park and campground operators secure the right coverage for over 20 years. Our team understands the unique risk profile of transient-guest operations and can structure a comprehensive program that protects your investment. Call 844-967-5247 for a free consultation.",
    ],
  },
  {
    slug: "manufactured-housing-community-property-insurance",
    title: "Protecting Your Manufactured Housing Community: Property Coverage Explained",
    excerpt:
      "Property insurance for manufactured housing communities involves more complexity than most owners realize. Replacement cost vs. actual cash value, infrastructure coverage, common area buildings, and loss of rents are all critical elements to get right.",
    featured: false,
    category: "Property Coverage",
    readTime: "10 min read",
    date: "May 20, 2026",
    dateISO: "2026-05-20",
    content: [
      "Property insurance is the foundation of any manufactured housing community owner's risk management program. But property coverage in this niche is significantly more complex than it is for conventional apartment buildings or commercial real estate — the ownership structure, infrastructure responsibilities, and regulatory environment all create unique challenges that require specialist knowledge to navigate effectively.",
      "## Understanding What You Own (and What You Don't)",
      "The fundamental starting point for manufactured housing community property insurance is understanding what the park owner actually owns. In most MHCs, the homes themselves are owned by the tenants — you own the land, the lot improvements, the shared utility systems, and any community buildings and amenities. This is a critical distinction, because it means your property insurance program must be calibrated to the value of your infrastructure and common areas, not the homes that happen to sit on your lots.",
      "In communities where the park owner operates park-owned homes (POHs) — either as rental units or as inventory awaiting sale — those homes must be separately scheduled on your property policy. POHs are insured on a per-unit basis with coverage for the structure, and often separately for any interior contents or appliances included in the rental.",
      "## Replacement Cost vs. Actual Cash Value",
      "The single most important decision in structuring your property coverage is whether to insure on a replacement cost (RC) or actual cash value (ACV) basis. This decision has enormous financial consequences in the event of a major loss.",
      "Actual cash value coverage pays the depreciated value of the damaged property — what it was worth at the time of the loss, accounting for age and wear. For a clubhouse built in 1985 or an electrical distribution system installed in 1992, ACV could be a fraction of what it actually costs to repair or replace. Many park owners who purchased the least expensive property policy available discover — at the worst possible time — that their ACV policy leaves them with hundreds of thousands of dollars in out-of-pocket repair costs.",
      "Replacement cost coverage pays what it actually costs to repair or rebuild the damaged property to its current condition, without deduction for depreciation. Yes, RC coverage costs more in premium. But the financial protection it provides in a significant loss event makes it worth the additional annual cost for most MHC owners.",
      "## Wind, Hail, and Severe Weather Coverage",
      "Manufactured housing communities face elevated weather-related property risks compared to conventional housing developments. Manufactured homes — even modern HUD-code homes — are more susceptible to wind damage than site-built construction. While the homes themselves are the tenants' responsibility to insure, severe weather can damage park infrastructure, community buildings, and utility systems.",
      "In markets with significant tornado, hurricane, or hail risk — which includes large portions of the South, Southeast, Midwest, and Plains states — wind and hail coverage may be subject to separate deductibles that can be substantially higher than your all-other-perils deductible. Review your policy declarations carefully to understand your weather-related deductibles, and ensure you understand how those deductibles apply (per-occurrence vs. per-structure) before a storm season begins.",
      "## Infrastructure Coverage: The Underground Challenge",
      "Underground utility infrastructure — water mains, sewer laterals, electrical conduit, gas distribution piping — is one of the most critical and most frequently uncovered assets at a manufactured housing community. Standard commercial property policies often exclude coverage for underground utilities entirely, or cover them only in limited circumstances.",
      "For a community with 100 or more lots, the underground utility infrastructure may represent $500,000 to $2 million or more in replacement value. A sewer main collapse, water main failure, or underground electrical fault can result in repair costs that run well into six figures — and if those assets are not explicitly covered on your policy, you will bear that cost entirely out of pocket.",
      "When reviewing your property policy with your insurance agent, specifically ask: Are underground utilities covered? Under what circumstances? At replacement cost or ACV? Is there a sublimit that applies to underground property? The answers to these questions can make a significant difference in your coverage picture.",
      "## Common Area Buildings and Amenities",
      "Clubhouses, swimming pools, laundry facilities, management offices, maintenance buildings, and other community amenities require specific attention in your property program. These buildings should be insured at their full replacement cost — obtain professional replacement cost appraisals every three to five years, as construction costs change significantly over time and out-of-date valuations are a common source of underinsurance.",
      "Swimming pools and recreational equipment require careful coverage attention. Pool structures, decking, filtration equipment, and pool fencing all have significant replacement values that must be reflected in your property policy. Specialized pool equipment, particularly for communities that offer elaborate aquatic amenities, may need to be separately scheduled.",
      "## Loss of Rents Coverage",
      "When a covered property loss renders lots uninhabitable — or when infrastructure failures prevent you from collecting rent — loss of rents coverage replaces that lost income during the restoration period. For manufactured housing community owners, loss of rents is not optional: a single significant infrastructure failure can affect dozens of income-producing lots simultaneously.",
      "The loss of rents period — the time covered by the policy while repairs are being made — should be adequate to cover realistic repair timelines. For major infrastructure losses, repair periods can extend to 12, 18, or even 24 months, particularly when permit delays, material shortages, or contractor availability issues are factored in. Ensure your loss of rents coverage includes a sufficient restoration period.",
      "## Practical Steps to Better Property Coverage",
      "Three actionable steps will significantly improve your MHC property coverage: First, obtain a professional replacement cost appraisal for all community buildings and infrastructure. Second, read your current policy's declarations and exclusions, paying particular attention to underground property, weather deductibles, and vacancy clauses. Third, work with a specialist MHC insurance agent who understands the unique property risks of manufactured housing communities and can place your coverage with carriers that have specific MHC expertise.",
      "Contractors Choice Agency specializes in insurance programs for manufactured housing communities and mobile home parks. Our team can identify coverage gaps in your current program and structure a comprehensive property solution that genuinely protects your investment. Contact us at 844-967-5247 or josh@contractorschoiceagency.com.",
    ],
  },
];
